In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.datasets import load_digits

In [4]:
#QUESTION1:
minist = load_digits()

In [6]:
minist.data.shape

(1797, 64)

In [8]:
#QUESTION2:
x = pd.DataFrame(np.array(minist.data))
y = pd.DataFrame(minist.target)

In [9]:
#QUESTION3:
X_train,X_test,Y_train,Y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [10]:
print("X_train: {}".format(X_train.shape))
print("X_test: {}".format(X_test.shape))
print("Y_train: {}".format(Y_train.shape))
print("Y_test: {}".format(Y_test.shape))

X_train: (1257, 64)
X_test: (540, 64)
Y_train: (1257, 1)
Y_test: (540, 1)


In [11]:
#QUESTION4:
model = LogisticRegression()
model.fit(X_train,Y_train)
predict = model.predict(X_test)

C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [13]:
from sklearn.neighbors import KNeighborsClassifier
kfold = model_selection.KFold(n_splits=10, random_state=7)
result1 = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')

C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:7

In [14]:
print("%.3f"%(result1.mean()*100))

95.227


In [17]:
result2 = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='neg_log_loss')
print(result2.mean()*100)

C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:7

-21.351389043688656


In [18]:
result3 = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='r2')
print(result3.mean()*100)

C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:7

86.99137509354499


In [21]:
result4 = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='neg_mean_squared_error')
print(result4.mean()*100)

C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:7

-104.9631746031746


In [22]:
result5 = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='neg_mean_absolute_error')
print(result5.mean()*100)

C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:7

-19.65396825396825


In [23]:
matrix = confusion_matrix(Y_test, predict)
print(matrix)

[[52  0  0  0  1  0  0  0  0  0]
 [ 0 43  1  0  0  0  0  0  6  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0 52  0  1  0  0  1  0]
 [ 0  1  0  0 59  0  0  0  0  0]
 [ 0  2  1  0  0 61  0  1  1  0]
 [ 0  0  0  0  0  1 52  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  1  0  0  0  1  0  0 41  0]
 [ 0  0  0  0  0  0  0  0  5 54]]


In [25]:
report = classification_report(Y_test, predict)
print(report)

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        53
           1       0.91      0.86      0.89        50
           2       0.96      1.00      0.98        47
           3       1.00      0.96      0.98        54
           4       0.98      0.98      0.98        60
           5       0.95      0.92      0.94        66
           6       1.00      0.98      0.99        53
           7       0.98      0.98      0.98        55
           8       0.76      0.95      0.85        43
           9       0.98      0.92      0.95        59

   micro avg       0.95      0.95      0.95       540
   macro avg       0.95      0.95      0.95       540
weighted avg       0.96      0.95      0.95       540

