In [3]:
import pandas as pd
import numpy as np

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [13]:
#QUESTION1:
minist = datasets.load_digits()
x = minist.data
y = minist.target

In [14]:
#QUESTION2:
sscaler = StandardScaler()
X = sscaler.fit_transform(x)

In [15]:
#QUESTION3:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [17]:
#QUESTION4:
pca =PCA(n_components=4)
pca_train = pca.fit_transform(X_train)
principalDf = pd.DataFrame(data=pca_train)

In [18]:
#QUESTION5:
le = LogisticRegression()
le.fit(X_train, Y_train)

C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\kanchan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [19]:
y_pred = le.predict(X_test)

In [21]:
#QUESTION6:
print("Accuracy score is: ",accuracy_score(Y_test, y_pred)*100)
print("\n")
print("Confusion matrix: ",confusion_matrix(Y_test, y_pred))
print("\n")
print("Classification report: ",classification_report(Y_test, y_pred))

Accuracy score is:  96.48148148148148


Confusion matrix:  [[53  0  0  0  0  0  0  0  0  0]
 [ 0 46  2  0  0  0  0  0  2  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  1 51  0  0  0  0  2  0]
 [ 0  1  0  0 59  0  0  0  0  0]
 [ 0  0  0  0  0 64  1  0  0  1]
 [ 0  0  0  0  0  1 52  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  1  0  0  0  1  0  0 41  0]
 [ 0  0  0  1  0  1  0  0  3 54]]


Classification report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        53
           1       0.96      0.92      0.94        50
           2       0.94      1.00      0.97        47
           3       0.98      0.94      0.96        54
           4       1.00      0.98      0.99        60
           5       0.96      0.97      0.96        66
           6       0.98      0.98      0.98        53
           7       1.00      0.98      0.99        55
           8       0.85      0.95      0.90        43
           9       0.96      0.92      0.94