In [10]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [13]:
iris = datasets.load_iris()

In [14]:
x = iris.data
y = iris.target

In [15]:
#QUESTION2:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [17]:
print("X_train: {}".format(X_train.shape))
print("X_test: {}".format(X_test.shape))
print("Y_train: {}".format(Y_train.shape))
print("Y_test: {}".format(Y_test.shape))

X_train: (105, 4)
X_test: (45, 4)
Y_train: (105,)
Y_test: (45,)


In [18]:
model = GaussianNB()

In [22]:
predict = model.predict(X_test)

In [23]:
model.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [25]:
matrix = confusion_matrix(Y_test,predict)
print(matrix)

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [26]:
report = classification_report(Y_test, predict)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

   micro avg       1.00      1.00      1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [27]:
MNB = MultinomialNB()

In [31]:
MNB.fit(X_train, Y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [32]:
pred = MNB.fit(X_train, Y_train).predict(X_test)

In [34]:
matrix = confusion_matrix(Y_test, pred)
print(matrix)

[[19  0  0]
 [ 0 12  1]
 [ 0  1 12]]


In [35]:
report = classification_report(Y_test, pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      0.92      0.92        13
           2       0.92      0.92      0.92        13

   micro avg       0.96      0.96      0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

